apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-awesome-front
spec:
  replicas: 2

  template:
    metadata:
      labels:
        app: front-chat

    spec:
      containers:   
      - name: front-app
        image: 10.101.91.182:5000/my-awesome-frontend-app:0.0.2
        imagePullPolicy: Always
