[environments]
  [environments.development]
    name = "frontend"
    namespace = "default"
    wait = true
    watch = true
    watch-delay = 8
    auto-connect = false
    dockerfile = ""
    chart = ""
