apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-app-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-app
spec:
  hosts:
  - "*"
  gateways:
  - frontend-app-gateway
  http:
  - route:
    - destination:
        host: frontend-app
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-app
spec:
  hosts:
  - "*"
  gateways:
  - frontend-app-gateway
  http:
  - route:
    - destination:
        host: frontendv2-app
        port:
          number: 3000
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend-app
spec:
  hosts:
  - backend-app
  http:
  - fault:
      abort:
        httpStatus: 500
        percent: 100
    route:
    - destination:
        host: backend-app
      weight: 100